#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PYTHON_BIN="${PYTHON_BIN:-python3}"


# -------------------- Manual selection (edit here) --------------------
task="run"                                    # run/val
output_file="result.json"
base_model="o3"
output_dir="${PROJECT_ROOT}/${base_model}/result_FULL"
dataset="princeton-nlp/SWE-bench_Multimodal"
dataset_split="test"
val_patch_no="1"                              # 1-n to validate; 0 to replay scenario
instance_id="${GUIREPAIR_INSTANCE_ID:-GoogleChrome}"   # supports full instance id, repo selector (e.g. PrismJS), or multiple selectors (e.g. "PrismJS highlightjs")

repo_path="${PROJECT_ROOT}/Reproduce_Scenario"
log_file="repair_${task}.log"
Code_Reply="True"
doc_RAG_query="False"
RAG_query="False"
keywords_searching="False"
Checked_Exception="True"
Patch_Check="False"
Patch_Select="True"
Overwrite_Code0="${GUIREPAIR_OVERWRITE_CODE0:-True}"
Variant_Gen_By_LLM="${GUIREPAIR_VARIANT_GEN_BY_LLM:-True}"
Variant_LLM_Only="${GUIREPAIR_VARIANT_LLM_ONLY:-True}"
Variant_Max_Chars="${GUIREPAIR_VARIANT_MAX_CHARS:-120000}"

File_Sort="True"
max_lines_per_snippet="500"
context_window="0"
bug_keywords_temperature="0.0"
bug_keywords_samples="1"
bug_docs_temperature="0.0"
bug_docs_samples="1"
code_reproduce_temperature="0.0"
code_reproduce_samples="1"
all_bug_file_temperature="1"
all_bug_file_samples="2"
max_candidate_bug_files="4"
max_candidate_doc_files="6"
key_bug_file_temperature="0.0"
key_bug_file_samples="1"
max_lines_per_key_file="500"
key_bug_class_function_temperature="0.7"
key_bug_class_function_samples="2"
line_level_fl_temperature="0.9"
line_level_fl_samples="40"
patch_generation_temperature="1"
patch_generation_samples="8"
ground_patch_generation_samples="1"
wait_time_after_api_request="0"
wait_time_after_build="0"

main_args=(
  --task "$task"
  --output_dir "$output_dir"
  --output_file "$output_file"
  --log_file "$log_file"
  --base_model "$base_model"
  --dataset "$dataset"
  --dataset_split "$dataset_split"
  --instance_id "$instance_id"
  --repo_path "$repo_path"
  --Code_Reply "$Code_Reply"
  --doc_RAG_query "$doc_RAG_query"
  --RAG_query "$RAG_query"
  --keywords_searching "$keywords_searching"
  --bug_keywords_temperature "$bug_keywords_temperature"
  --bug_keywords_samples "$bug_keywords_samples"
  --bug_docs_temperature "$bug_docs_temperature"
  --bug_docs_samples "$bug_docs_samples"
  --max_candidate_doc_files "$max_candidate_doc_files"
  --code_reproduce_temperature "$code_reproduce_temperature"
  --code_reproduce_samples "$code_reproduce_samples"
  --Checked_Exception "$Checked_Exception"
  --max_lines_per_snippet "$max_lines_per_snippet"
  --context_window "$context_window"
  --all_bug_file_temperature "$all_bug_file_temperature"
  --all_bug_file_samples "$all_bug_file_samples"
  --max_candidate_bug_files "$max_candidate_bug_files"
  --key_bug_file_temperature "$key_bug_file_temperature"
  --key_bug_file_samples "$key_bug_file_samples"
  --max_lines_per_key_file "$max_lines_per_key_file"
  --key_bug_class_function_temperature "$key_bug_class_function_temperature"
  --key_bug_class_function_samples "$key_bug_class_function_samples"
  --line_level_fl_temperature "$line_level_fl_temperature"
  --line_level_fl_samples "$line_level_fl_samples"
  --patch_generation_temperature "$patch_generation_temperature"
  --patch_generation_samples "$patch_generation_samples"
  --ground_patch_generation_samples "$ground_patch_generation_samples"
  --wait_time_after_api_request "$wait_time_after_api_request"
  --wait_time_after_build "$wait_time_after_build"
  --val_patch_no "$val_patch_no"
  --Patch_Check "$Patch_Check"
  --Patch_Select "$Patch_Select"
  --Overwrite_Code0 "$Overwrite_Code0"
  --Variant_Gen_By_LLM "$Variant_Gen_By_LLM"
  --Variant_LLM_Only "$Variant_LLM_Only"
  --Variant_Max_Chars "$Variant_Max_Chars"
  --File_Sort "$File_Sort"
)

"$PYTHON_BIN" "${SCRIPT_DIR}/main.py" \
  "${main_args[@]}"
